---
# defaults file for strimzi-kafka
strimzi_namespace: kafka
strimzi_version: "0.45.0"
kafka_cluster_name: messenger-kafka
kafka_replicas: 3
kafka_storage_size: "20Gi"
kafka_retention_hours: 168

kafka_topics:
  - name: message.created
    partitions: 6
    replicas: 3
    config:
      retention.ms: "604800000"
      cleanup.policy: delete
  - name: chat.events
    partitions: 6
    replicas: 3
    config:
      retention.ms: "604800000"
      cleanup.policy: delete
  - name: receipt.events
    partitions: 6
    replicas: 3
    config:
      retention.ms: "604800000"
      cleanup.policy: delete
  - name: presence.events
    partitions: 6
    replicas: 3
    config:
      retention.ms: "604800000"
      cleanup.policy: delete
