apiVersion: v1
kind: ServiceAccount
metadata:
  name: chat-service
  namespace: chat-service
  labels:
    app.kubernetes.io/name: chat-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: message-service
  namespace: message-service
  labels:
    app.kubernetes.io/name: message-service
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: realtime-gateway
  namespace: realtime-gateway
  labels:
    app.kubernetes.io/name: realtime-gateway
