apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: message-service-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/KamilNabiullin/message_service.git
    targetRevision: main
    path: messenger-infra/k8s/helm-charts/message-service
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: message-service
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
