apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/DanielGim-Hub/chatService.git
    targetRevision: main
    path: messenger-infra/observability
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
