apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: realtime-gateway-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/chozahe/realtime_service.git
    targetRevision: main
    path: messenger-infra/k8s/helm-charts/realtime-gateway
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: realtime-gateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
