# Generated by Django 5.2.12 on 2026-03-22 13:08

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSequenceCounter',
            fields=[
                ('chat_id', models.UUIDField(primary_key=True, serialize=False)),
                ('last_sequence', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Chat sequence counter',
                'verbose_name_plural': 'Chat sequence counters',
                'db_table': 'chat_sequence_counters',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chat_id', models.UUIDField(db_index=True)),
                ('sender_id', models.UUIDField(db_index=True)),
                ('content_type', models.CharField(choices=[('text', 'text'), ('attachment', 'attachment'), ('system', 'system')], max_length=20)),
                ('text', models.TextField(blank=True, null=True)),
                ('attachment', models.JSONField(blank=True, null=True)),
                ('reply_to_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sent', 'sent'), ('delivered', 'delivered'), ('read', 'read'), ('deleted', 'deleted')], default='sent', max_length=20)),
                ('sequence_number', models.BigIntegerField()),
                ('idempotency_key', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'messages',
                'ordering': ['sequence_number'],
                'indexes': [models.Index(fields=['chat_id', 'sequence_number'], name='msg_chat_seq_idx'), models.Index(fields=['chat_id', 'sender_id', 'created_at'], name='msg_chat_sender_created_idx'), models.Index(fields=['chat_id', 'created_at'], name='msg_chat_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('chat_id', 'sequence_number'), name='messages_chat_sequence_unique')],
            },
        ),
        migrations.CreateModel(
            name='MessageVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_id', models.UUIDField(db_index=True)),
                ('chat_id', models.UUIDField(db_index=True)),
                ('version', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Message version',
                'verbose_name_plural': 'Message versions',
                'db_table': 'message_versions',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['message_id', 'created_at'], name='msg_ver_message_created_idx')],
                'constraints': [models.UniqueConstraint(fields=('message_id', 'version'), name='message_versions_unique_version')],
            },
        ),
        migrations.CreateModel(
            name='OutboxEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('event_type', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('partition_key', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('published', 'published'), ('failed', 'failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('retry_count', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Outbox event',
                'verbose_name_plural': 'Outbox events',
                'db_table': 'outbox_events',
                'indexes': [models.Index(fields=['status', 'created_at'], name='outbox_status_created_idx'), models.Index(fields=['published_at'], name='outbox_published_idx')],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.UUIDField()),
                ('user_id', models.UUIDField()),
                ('chat_id', models.UUIDField(db_index=True)),
                ('status', models.CharField(choices=[('delivered', 'delivered'), ('read', 'read')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Receipt',
                'verbose_name_plural': 'Receipts',
                'db_table': 'receipts',
                'indexes': [models.Index(fields=['chat_id', 'message_id'], name='receipt_chat_message_idx'), models.Index(fields=['user_id', 'chat_id', 'updated_at'], name='receipt_user_chat_updated_idx')],
                'constraints': [models.UniqueConstraint(fields=('message_id', 'user_id'), name='receipts_message_user_unique')],
            },
        ),
    ]
